"""Core domain logic, models, and orchestration for OCR-LLM-Local."""

from .client import (
    BadRequestError,
    ClientError,
    ResponseParsingError,
    ServerError,
    ServerOfflineError,
    ServerTimeoutError,
    VisionClient,
    resolve_chat_endpoint,
)
from .constants import SUPPORTED_EXTENSIONS, __version__
from .engine import OCREngine
from .formatter import (
    format_output,
    resolve_unique_stem,
    sanitize_filename_stem,
    save_artifacts,
)
from .hardware import (
    HardwareProfile,
    PINNED_LLAMA_BUILD,
    clear_hardware_cache,
    detect_hardware,
    get_cached_hardware_profile,
)
from .models import (
    JobConfig,
    JobStatus,
    OCRResult,
    OutputFormat,
    PageResult,
    PROMPT_PRESETS,
)
from .pipeline import (
    CorruptDocumentError,
    EmptyDocumentError,
    EncryptedDocumentError,
    ExtractedPage,
    FilePreflightError,
    MAX_RASTER_PIXELS,
    PipelineError,
    UnsupportedFormatError,
    check_preflight,
    ingest,
    is_pdf,
)
from .runtime_manager import (
    RuntimeDownloadError,
    RuntimeIntegrityError,
    RuntimeManagerError,
    RuntimeValidationError,
    ZipSlipSecurityError,
    ensure_runtime,
    get_installed_runtime_path,
    is_runtime_installed,
)
from .server_manager import (
    ServerManager,
    ServerOwnership,
    ServerStatus,
    ServerStatusInfo,
    probe_server_health,
)

__all__ = [
    "BadRequestError",
    "ClientError",
    "CorruptDocumentError",
    "EmptyDocumentError",
    "EncryptedDocumentError",
    "ExtractedPage",
    "FilePreflightError",
    "HardwareProfile",
    "JobConfig",
    "JobStatus",
    "MAX_RASTER_PIXELS",
    "OCREngine",
    "OCRResult",
    "OutputFormat",
    "PINNED_LLAMA_BUILD",
    "PageResult",
    "PipelineError",
    "PROMPT_PRESETS",
    "ResponseParsingError",
    "RuntimeDownloadError",
    "RuntimeIntegrityError",
    "RuntimeManagerError",
    "RuntimeValidationError",
    "SUPPORTED_EXTENSIONS",
    "ServerError",
    "ServerManager",
    "ServerOfflineError",
    "ServerOwnership",
    "ServerStatus",
    "ServerStatusInfo",
    "ServerTimeoutError",
    "UnsupportedFormatError",
    "VisionClient",
    "ZipSlipSecurityError",
    "check_preflight",
    "clear_hardware_cache",
    "detect_hardware",
    "ensure_runtime",
    "format_output",
    "get_cached_hardware_profile",
    "get_installed_runtime_path",
    "ingest",
    "is_pdf",
    "is_runtime_installed",
    "probe_server_health",
    "resolve_chat_endpoint",
    "resolve_unique_stem",
    "sanitize_filename_stem",
    "save_artifacts",
    "__version__",
]


